### ISSUE TITLE
Event History Error

### ISSUE THREAD

**Issue by mkg1856** [625alex/SmartTiles#1]
Good Morning,

I was wondering if anyone else was having an issue with the Event History displaying.  When I try to view I receive the following error: "error groovy.lang.missingmethodexception" .  Any help would be greatly appreciated.

Mike

**Comment by CosmicPuppy** [comment]
Thanks.

This is a known new bug with version 5.6.1. We're looking into it.

**Comment by mkg1856** [comment]
Thanks Terry!

Mike

**Comment by CosmicPuppy** [comment]
**I just deployed a bug-fix; v5.6.1+009.**

@mkg1856: _Please let me know if it's working now, ... thanks!_

**Comment by mkg1856** [comment]
Its working now Terry.  Thanks so much!
