### ISSUE TITLE
Hygrometer humidity error

### ISSUE THREAD

**Issue by iakoubtchik** [625alex/SmartTiles#6]
**trace** humidity from Livingroom was provided with handler...creating subscription
**error** Device Livingroom (humidity) does not report humidity properly. This is probably due to numerical value returned as text

v 4.3

**Comment by 625alex** [comment]
ST Humidity/Temperature device handler is broken in ST cloud. They are aware of this and will fix it eventually.

**Comment by iakoubtchik** [comment]
Got it... thank you!
