### ISSUE TITLE
How do you make changes to the Nest with this Dashboard?

### ISSUE THREAD

**Issue by thehands1** [625alex/SmartTiles#7]
I have a Nest thermostat and this dashboard only shows the temperature and not the other items or allows me to change anything is there a way to do that, or do I need to use another dashboard or link?  Great app so far!!!

**Comment by 625alex** [comment]
This is listed as "coming soon" on the forum. So, coming soon.

**Comment by hiphopsmurf** [comment]
I have to agree that this is an awesome app! Has adding support for the Nest Protect made it on the coming soon list also?

**Comment by 625alex** [comment]
I don't plan to integrate fire/smoke alarms into the dashboard. If there is
a fire, you better have something that makes noise. I don't think it will
help much if you keep staring at the Fire Tile to see if it's state will
ever change.

**Comment by hiphopsmurf** [comment]
I was actually more interested in the battery feature. Currently it returns the values of "Low" or "Good" which displays NULL on the current dashboard. While I am pretty good at figuring things out, I have been messing with your code and have been unable to parse "currentValue" to text. (Still a little wet behind the ears when it comes to groovy)

**Comment by 625alex** [comment]
Nest Protect device handler does not implement battery capability properly.
If Nest Protect device handler is fixed, it will work with the dashboard.

**Comment by 625alex** [comment]
Thermostat controls are implemented as of version 5.0.

Nest Protect will not be added as such. If it implements official SmartThings battery capability, it is already compatible with SmartTiles. 

I don't intend implementing Smoke Alarm capability.
